/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author usuario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /** Creates new form VistaPrincipal */
    public VistaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        mnb_Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_Salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_GestionMonitores = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mi_GestionSocios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mi_SociosInscritos = new javax.swing.JMenuItem();
        miAdministrarSocios = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Salir");

        mi_Salir.setLabel("Salir de la aplicación");
        jMenu1.add(mi_Salir);

        mnb_Menu.add(jMenu1);

        jMenu2.setText("Monitores");

        mi_GestionMonitores.setText("Gestión de Monitores");
        jMenu2.add(mi_GestionMonitores);

        mnb_Menu.add(jMenu2);

        jMenu3.setText("Socios");

        mi_GestionSocios.setText("Gestión de Socios");
        jMenu3.add(mi_GestionSocios);

        mnb_Menu.add(jMenu3);

        jMenu5.setText("Actividades");

        mi_SociosInscritos.setText("Socios Inscritos");
        jMenu5.add(mi_SociosInscritos);

        miAdministrarSocios.setText("Administrar Socios");
        jMenu5.add(miAdministrarSocios);

        mnb_Menu.add(jMenu5);

        setJMenuBar(mnb_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    public javax.swing.JMenuItem miAdministrarSocios;
    public javax.swing.JMenuItem mi_GestionMonitores;
    public javax.swing.JMenuItem mi_GestionSocios;
    public javax.swing.JMenuItem mi_Salir;
    public javax.swing.JMenuItem mi_SociosInscritos;
    private javax.swing.JMenuBar mnb_Menu;
    // End of variables declaration//GEN-END:variables

}
